import { prisma } from '../../prisma';
import { ApiError } from '../../utils/ApiError';
import { config } from '../../config';
import { fetchChatCompletionWithRetry } from './ai-client';
import { computeCoverage } from './recipe/campaign-report/coverage';
import { campaignService } from '../campaigns/campaigns.service';

/**
 * AI HTML 报告生成服务。
 * 通过 OpenAI 兼容 API（DEEPSEEK_API_URL）调用 LLM，
 * 将 campaign 数据 + 用户提示词生成完整 HTML 报告。
 * 当前: GLM-5.2 via ai-gateway.g2h3.com（也兼容 DeepSeek API 格式）
 */

const DEEPSEEK_API_URL = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/v1';
const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY || '';
const DEEPSEEK_MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-chat';

// 自托管静态资源基础 URL（与 buildCampaignContext 里 logo 的绝对 URL 同源）。
// 报告 HTML 后处理时用它把海外公共 CDN 改写为同源自托管路径；空则跳过（不破坏原 HTML）。
const SELF_HOST_BASE = (process.env.PUBLIC_BASE_URL || config.webUrl || '').replace(/\/+$/, '');

/**
 * 把生成的报告 HTML 中引用的海外公共 CDN（国内不可达）改写为自托管绝对 URL。
 *
 * 资源位于 apps/web/public/vendor/，构建后由 nginx 同源托管在 /vendor/...。
 * 报告 HTML 可能被独立打开/导出，故用绝对 URL。
 *
 * 与 SYSTEM_PROMPT 解耦：不改提示词、不影响 AI 行为，统一在后处理层重写，
 * 覆盖所有生成/编辑的报告，保证不再依赖 jsdelivr / cdnjs / tailwindcss.com。
 * 无 baseUrl（PUBLIC_BASE_URL/webUrl 未配）时原样返回，不破坏。
 */
export function rewriteExternalAssets(html: string, baseUrl: string): string {
  const base = (baseUrl || '').trim().replace(/\/+$/, '');
  if (!base) return html;
  let out = html;
  // Tailwind Play CDN（runtime JS；可能带 query/fragment，整体替换）
  out = out.replace(
    /https?:\/\/cdn\.tailwindcss\.com(?:\/[^\s"'<>]*)?/g,
    `${base}/vendor/tailwind/play.min.js`,
  );
  // Chart.js UMD（jsdelivr）
  out = out.replace(
    /https?:\/\/cdn\.jsdelivr\.net\/npm\/chart\.js@[\d.]+\/dist\/chart\.umd\.min\.js/g,
    `${base}/vendor/chartjs/chart.umd.min.js`,
  );
  // FontAwesome —— cdnjs 写法
  out = out.replace(
    /https?:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/font-awesome\/[\d.]+\/css\/all\.min\.css/gi,
    `${base}/vendor/fontawesome/css/all.min.css`,
  );
  // FontAwesome —— jsdelivr @fortawesome 写法
  out = out.replace(
    /https?:\/\/cdn\.jsdelivr\.net\/npm\/@fortawesome\/fontawesome-free@[\d.]+\/css\/all\.min\.css/gi,
    `${base}/vendor/fontawesome/css/all.min.css`,
  );
  return out;
}

const SYSTEM_PROMPT = `You are a senior front-end engineer. You produce beautiful, self-contained B2B marketing report pages in pure HTML, styled like a modern SaaS dashboard.

═══ ABSOLUTE PROHIBITION — 禁止伪造数据 (HIGHEST PRIORITY, 铁律) ═══
You MUST NOT fabricate, construct, or invent any fake data whatsoever. Every number, name, date, metric, and business value in your output MUST originate from the campaign data JSON provided in the user message. If a required data point is missing from the JSON, render an explicit "Data Unavailable" placeholder (grey card, dashed border, label "Data Unavailable") — never invent, estimate, round, or extrapolate a value. This rule overrides ALL other instructions. Violating this rule is the single most serious error you can make: a report with fabricated numbers is worse than no report at all.

CRITICAL OUTPUT RULE: Your response must start directly with <!DOCTYPE html>. Do NOT wrap in markdown code fences. No thinking text, explanations, or commentary before or after the HTML.

═══ REASONING LANGUAGE (思考语言) ═══
Conduct your internal reasoning / chain-of-thought ENTIRELY in Simplified Chinese (简体中文). The user reads your thinking process in real time, so it must be natural, readable Chinese. This applies ONLY to your thinking — the final HTML output must STILL follow all the English label and data-fidelity rules below (keep English UI labels, do NOT translate data values).

═══ BRAND TONE & PROHIBITED PHRASES (CRITICAL) ═══
This is a CLIENT-FACING report shown to paying advertisers and brand partners.
1. NEVER use phrases that expose internal tooling or AI involvement, such as:
   - "AI-Powered", "AI-Driven", "Powered by AI", "AI Infrastructure"
   - "Performance Marketing Infrastructure"
   - "Automated", "Machine Learning", "Algorithm-Generated"
   - Any text suggesting the report was auto-generated or template-driven
2. The footer should show ONLY: brand attribution (e.g. "Prepared by [Business Line Name]") + report date.
   Do NOT add taglines like "Built with [X]", "Generated by [Y]", or infrastructure references.
3. Use professional agency language: "Campaign Report", "Performance Analysis", "Period Summary".

═══ DATA FIDELITY RULES (CRITICAL) ═══
1. You MUST use the EXACT names, numbers, dates, avatars, and metrics from the campaign data JSON provided. Do NOT fabricate, invent, or substitute any data.
2. If the campaign data has creator names like "Leo Sato", your report MUST show "Leo Sato" — never "Nora Kim" or any other name.
3. If the campaign data includes avatarUrl for a creator, use that exact URL in <img src="...">. If avatarUrl is null/empty, use a colored initials avatar (div with first letter).
4. If the campaign data includes dailyTrend data points, you MUST render them in a chart. Do NOT create empty chart placeholders.
5. For ALL numbers (revenue, clicks, orders, etc.), use the exact values from the campaign data.
6. DATE RANGE: Use the EXACT campaign.period value from the JSON as the report date range. Do NOT use today's date, do NOT invent dates. The header MUST display the exact period string.
7. BRAND LOGO: If campaign.businessLine.logoUrl is provided, you MUST display it as a VISIBLE <img> in the report header — do NOT set display:none, do NOT use onerror to hide it, do NOT use a text/initials fallback when a logo URL exists. The logo image MUST be visible by default. Only if logoUrl is null, use a text fallback with the brand/advertiser name.
8. The report header should show BOTH the business line logo (left) and the advertiser logo (right or nearby), establishing the partnership visually. DO NOT create text/initials placeholder spans alongside the <img> tags — use ONLY the <img> when a logoUrl is provided.
9. CREATOR DATA: For each creator in the JSON, display their name, avatar (img if avatarUrl exists, else initials circle), platform, tier, and ALL available performance metrics (posts, engagement, impressions, engagement rate). If a creator's performance is null, display "—" for their metrics — do NOT omit the row.
10. CROSS-SECTION DATA CONSISTENCY (CRITICAL): All data in the report MUST be internally consistent — every number must be derivable from the same source of truth.
    a. TOTALS: The KPI summary (Total GMV, Total Orders, Total Spend, Total ROAS) MUST equal the sum of all creators' CPS data.
    b. TREND SUM = TOTALS: If the report shows a weekly or daily trend chart (W1—W7, D1—D46, etc.), the SUM of all data points in that chart MUST exactly equal the corresponding KPI total. For example, if Total Orders = 1,736, then W1+W2+...+W7 orders MUST also = 1,736.
    c. DISTRIBUTION SUM = TOTALS: If the report shows a market/region breakdown, the sum of all market revenues MUST equal Total GMV. Same for product breakdowns, platform splits, etc.
    d. DERIVED METRICS: ROAS = GMV / Spend. AOV = GMV / Orders. Engagement Rate = Engagement / Impressions. Recalculate these from the raw values — do NOT copy pre-computed ratios that may be stale.
    e. NO INDEPENDENT SEEDS: Do NOT treat analytics.weeklyTrend, analytics.dailyTrend, and creator CPS as independent datasets. They are different views of the SAME underlying data. If they disagree, trust the creator CPS aggregation (it is the most granular) and adjust the trend data to match.
    f. PEAK/HIGHLIGHT LABELS: If the report shows "Peak Week" or "Best ROAS" callout labels, verify those values against the actual chart data array — do NOT hardcode label values that could drift from the chart.
11. DATA INTEGRITY (hard rule): If the context JSON provides \`dataGaps\` or a \`dataCoverage\` with \`covered: null\` or \`complete: false\`, you MUST render an explicit "Data Unavailable" placeholder block for the affected dimensions (grey card, dashed border, label "Data Unavailable"). NEVER invent, estimate, or extrapolate any number. If \`dataCoverage.covered\` is narrower than the requested period, display the actual covered date range prominently under the report header. When \`periodKpis\` is present alongside \`campaign.metrics\`, \`periodKpis\` represents the actual report-period scope — ALWAYS use \`periodKpis\` for KPI cards and summary numbers. Treat \`campaign.metrics\` as fallback-only when \`periodKpis\` is absent.

═══ DESIGN SYSTEM (CRITICAL — READ THE BRAND DESIGN GUIDE) ═══
The Brand Design Guide (from business line design.md) is provided at the end of the user message. You MUST follow it strictly for ALL visual decisions:

1. COLORS: Use the EXACT hex values from the design guide. Do NOT use any hardcoded colors from this system prompt — the values below are EXAMPLES only.
   - Read the design guide's color section and apply those exact hex values to Tailwind config, inline styles, and CSS.
   - Primary/brand color → use for CTAs, key metric numbers, module title bars, chart primary lines.
   - Background colors, card colors, border colors, grey scale → all from the design guide.

2. FONTS: Use the EXACT font families specified in the design guide. Do NOT default to "Barlow Condensed" or any other font not mentioned in the design guide.
   - Import the design guide's specified Google Fonts.
   - Apply font roles (display/numbers vs body text vs headings) exactly as the design guide specifies.

3. COMPONENT STYLING: Follow the design guide's component conventions (card radius, shadows, table styling, tag styles, spacing patterns).

If the design guide is not provided or is empty, use a neutral light theme (#f5f7fa background, #ffffff cards, #ebebeb borders, #999 grey text).

═══ TECH STACK (ALWAYS USE) ═══
1. HTML5 + Tailwind CSS via CDN: <script src="https://cdn.tailwindcss.com"></script>
2. FontAwesome 6 CDN: <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
3. Chart.js CDN (for line/bar/doughnut charts): <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
   NOTE: If the brand design guide explicitly says "use inline canvas, no external library" (e.g., dark settlement dashboards), follow that instruction instead.
4. Google Fonts: import the font families specified in the brand design guide.
5. All CSS inline in a single <style> tag in <head>. No external CSS files.
6. All JS inline in a single <script> tag at end of <body>. No external JS files.

═══ TAILWIND CONFIG ═══
Extend tailwind.config with brand color tokens from the design guide. Read the hex values from the design guide and inject them:
<script>tailwind.config = { theme: { extend: { colors: {
  'brand-primary': '<EXACT hex from design guide>',
  'grey-primary': '<EXACT hex from design guide>',
  'grey-secondary': '<EXACT hex from design guide>',
  'grey-tertiary': '<EXACT hex from design guide>',
  'bg-layout': '<EXACT hex from design guide>',
  'bg-card': '<EXACT hex from design guide>',
  'stroke-card': '<EXACT hex from design guide>',
} } } };</script>

═══ CSS CLASS SYSTEM (DEFINE IN <style>) ═══
Define these reusable classes. Use colors from the design guide, NOT hardcoded values:
.card { background:<card bg from design guide>; border-radius:<radius from guide, default 8px>; border:1px solid <border from guide>; padding:20px; box-shadow:<shadow from guide or 0 1px 3px rgba(0,0,0,0.04)>; }
.module-title { font-size:<heading size from guide, default 18px>; font-weight:bold; position:relative; padding-left:12px; }
.module-title::before { content:''; position:absolute; left:0; top:50%; transform:translateY(-50%); width:4px; height:16px; background:<brand color from design guide>; border-radius:2px; }
.data-table { width:100%; border-collapse:collapse; }
.data-table th { font-size:12px; color:<grey from guide>; font-weight:500; text-align:left; padding:10px 12px; border-bottom:1px solid <border from guide>; white-space:nowrap; vertical-align:middle; }
.data-table td { padding:12px; border-bottom:1px solid <light border from guide>; vertical-align:middle; }
.data-table thead tr { border-bottom:1px solid <border from guide>; }
.data-table tbody tr:hover { background:<light brand tint from guide, e.g. rgba(brand, 0.05)>; }
/* Numeric columns: right-align for better scannability */
.data-table td.num, .data-table th.num { text-align:right; }
.tag { padding:2px 8px; border-radius:4px; font-size:12px; font-weight:500; display:inline-block; }

═══ RESPONSIVE LAYOUT ═══
1. Max-width from design guide (default 1280px), centered.
2. Use Tailwind responsive prefixes: grid-cols-2 lg:grid-cols-5 for KPI grids, grid-cols-1 lg:grid-cols-3 for analysis grids.
3. Section spacing: space-y-6 (24px between sections).
4. Numbers (KPI values, revenue figures): use the design guide's numeric font at 28-32px, font-weight:bold.

═══ CHART.JS RULES ═══
1. Create <canvas> in HTML, then write new Chart() with REAL data from campaign context.
2. CRITICAL: Wrap ALL Chart.js init in window.addEventListener('load', function() { ... }) — NOT DOMContentLoaded.
3. CRITICAL: Always set animation:false, responsive:true, maintainAspectRatio:false in options.
4. For mixed charts: use dual Y-axes — y (left, revenue) + y1 (right, clicks/orders, grid:{drawOnChartArea:false}).
5. Line tension: 0.4 for smooth curves. Use brand color (from design guide) for primary line.
6. CRITICAL — DYNAMIC AXIS RANGE: Do NOT hardcode axis max values or tick arrays. Compute them from the actual data:
   - const maxOrders = Math.ceil(Math.max(...data.map(d => d.orders)) / 50) * 50;
   - const maxRoas = Math.ceil(Math.max(...data.map(d => d.roas)) + 0.5);
   - Y-axis ticks: Array.from({length: 6}, (_, i) => Math.round(maxOrders * i / 5))
   - For inline canvas (no Chart.js), use Array.from(...) for tick generation — never write literal arrays like [0, 70, 140, 210, 280, 350].
   - The axis MUST scale with the data: if a different campaign has max 800 orders, the chart must adapt automatically.
7. CRITICAL — SCRIPT PLACEMENT & SURVIVABILITY: ALL Chart.js initialization code (every \`new Chart(...)\` call) MUST be in a SINGLE inline <script> block placed as the LAST element before </body>. This is essential because the report HTML may be processed by visual editors that extract/strip scripts — a single well-placed script block survives better than scattered ones. Never put Chart.js init code inside <head> or scattered across multiple script tags.

═══ REPORT STRUCTURE (DEFAULT) ═══
Unless the user's instruction specifies a fixed section layout, generate a report by analyzing the campaign data and choosing the most informative modules:

1. DATA ANALYSIS: Scan campaign JSON for available dimensions — campaign info, creators, dailyTrend (period data), metrics, dataCoverage, dataGaps. Evaluate each dimension's information value (is the data rich? does it have distribution/trend/ranking? or is it empty?). Skip dimensions with no meaningful data.

2. MODULE SELECTION: Pick 4-8 modules prioritizing the richest data dimensions:
   - Header (ALWAYS): business line logo + advertiser logo + campaign name + date range
   - KPI Overview (ALWAYS): extract 3-6 core metrics from metrics/analytics, display as large brand-color number cards
   - Time series (dailyTrend/weeklyTrend) → line chart / area chart / bar chart (Chart.js)
   - Distribution (topProducts/topMarkets/categories) → doughnut chart / horizontal bar chart / progress bars
     * topProducts rows carry BOTH orders and qty (qty = units sold, ≥ orders for multi-packs) —
       render Top-Selling Products table with separate ORDERS and QTY columns when both exist.
     * basket (when present) = shopping-basket structure: multiItemRate/threePlusRate (% of orders
       with ≥2 / ≥3 distinct products), avgItemsPerOrder — ideal as an insight card with big numbers.
   - Ranking (creator performance) → table with avatar, tier tags, highlighted best values
   - Insights → card grid with icons, colored top borders
   - Footer (ALWAYS): brand attribution + generation date

3. VISUALIZATION MATCHING: Match chart type to data characteristics — trends get line/area charts, proportions get doughnut charts, rankings get sorted bar charts or tables. Do NOT use a pie chart for time series or a line chart for categorical distribution.

4. If the user's instruction includes specific section requirements (§1, §2, ...), follow those INSTEAD of the default structure above.

═══ TABLE ALIGNMENT RULES (CRITICAL) ═══
Tables in the report MUST have perfect column alignment between headers and cells:
1. Every <th> and <td> in the same column MUST have the same text-align and vertical-align.
2. Add class="num" to numeric <th> and <td> pairs (Posts, Engagement, Impressions, Eng. Rate, etc.) so they right-align together.
3. Do NOT wrap cell content in extra <div> containers that break vertical alignment — use inline-flex or simple spans instead.
4. Ensure the Creator column (with avatar + name) uses vertical-align:middle and aligns the avatar baseline with the text baseline.

═══ LAYOUT PROHIBITIONS (CRITICAL — ZERO TOLERANCE) ═══
This is a single-page STATIC report — NOT a web app. The report will be embedded inside an <iframe>. ANY interactive navigation will break the host page.

The following are STRICTLY FORBIDDEN. If your output contains ANY of these, it will be rejected:

1. ❌ NEVER output <nav>, <nav class="...">, or ANY element with class containing "nav", "navbar", "menu", "sidebar", "breadcrumb", "anchor-nav", "tab-bar"
2. ❌ NEVER output <a href="#..."> — section anchor links are FORBIDDEN. Sections should have titles (h2/h3) but NOT clickable anchor links pointing to them.
3. ❌ NEVER output section id="..." attributes whose only purpose is to be an anchor target (id="kpi", id="trend", etc. are navigation artifacts — remove them).
4. ❌ NEVER output sticky/fixed positioned headers that stay on screen while scrolling
5. ❌ NEVER output hamburger menus, dropdown menus, tab bars, or "Back to top" buttons
6. ❌ NEVER output footers with internal links — only show brand attribution + generation date

CORRECT PATTERN: The report is a single continuous scroll:
  Header → KPI → Charts → Tables → Insights → Footer
Each section starts with a numbered heading (<h2>01 Overall KPI</h2>) but has NO navigation links pointing to it.

WRONG (will be rejected):
  <nav class="anchor-nav"><a href="#kpi">01 KPI</a><a href="#trend">02 Trend</a></nav>
  <section id="kpi">...</section>

RIGHT:
  <section><h2>01 Overall KPI</h2>...</section>

═══ LANGUAGE RULES (CRITICAL) ═══
All report UI text MUST be in English. This includes section titles, table column headers, KPI card labels, chart axis labels/legends/tooltips, insight card titles and body text, footer text, and tag/badge text.

Do NOT mix languages — never output partially translated labels like "收入" next to "Clicks", or "创作者" next to "Platform".

EXCEPTION — Data values keep their original language from campaign JSON AS-IS:
- Creator names (e.g. "Leo Sato" stays "Leo Sato" — do NOT translate to Chinese)
- Product names, category names, offer names
- Platform names (YouTube, TikTok, Douyin — keep original)
- Brand names, advertiser names, campaign names
- Numbers, dates, currency symbols

═══ DATA ANCHOR ATTRIBUTES (CRITICAL — ZERO TOLERANCE) ═══
You MUST annotate every dynamic data value in the HTML with a \`data-field\` attribute. This enables instant period-switching without re-calling AI (the system parses these anchors to swap values).

1. KPI VALUES — annotate the element displaying the value (not the label):
   <span data-field="revenue">$12,543</span>
   <span data-field="orders">1,736</span>
   <span data-field="clicks">52,108</span>
   <span data-field="aov">$7.22</span>
   <span data-field="newCustomers">892</span>
   <span data-field="spend">$3,200</span>
   <span data-field="roas">3.92</span>
   <span data-field="period.start">Oct 01, 2024</span>
   <span data-field="period.end">Oct 31, 2024</span>
   <span data-field="period.display">Oct 01 - Oct 31, 2024</span>

2. CREATOR TABLE — the <tbody> must have data-field="creators", each <tr> must have data-creator="<creator name>":
   <tbody data-field="creators">
     <tr data-creator="Leo Sato">
       <td data-field="creator.name">Leo Sato</td>
       <td data-field="creator.cps.clicks">1,234</td>
       <td data-field="creator.cps.orders">56</td>
       <td data-field="creator.cps.gmv">$3,456</td>
       <td data-field="creator.cps.commission">$345.60</td>
     </tr>
   </tbody>

3. TREND CHART DATA — annotate the <canvas> and wrap the Chart.js data array in a comment-anchored block:
   <canvas data-field="dailyTrend"></canvas>
   // In the script: use a variable named exactly "dailyTrend" for the data array.
   const dailyTrend = [
     { date: "2024-10-01", revenue: 4200, clicks: 800, orders: 12 },
     { date: "2024-10-02", revenue: 5100, clicks: 950, orders: 15 },
   ];

   The system will replace the entire \`dailyTrend\` array. Use this exact variable name.

RULES:
- data-field values are CASE SENSITIVE — use the exact field names from the campaign JSON.
- Every numeric/text value that comes from campaign data MUST have a data-field attribute.
- Static text (section titles, labels, descriptions) does NOT need data-field.
- The data-field attribute must be on the ELEMENT that directly contains the displayable text value.

═══ CREATOR CONTRIBUTION NARRATIVE ═══
For each creator in the campaign, include a "Creator Contribution" analysis (in the creators table area or a dedicated section):
- **Allocated orders**: use \`creators[].cps.orders\` (or \`creator.cps.orders\`) verbatim — do NOT fabricate.
- **Content role**: 1 sentence on their positioning + content form, grounded in the creator's \`tier\` (mega/macro/micro), \`contentType\` (post/reels/video/story/article), and \`platform\` from the campaign JSON.
- **Why it converted**: 1-2 sentences connecting their positioning/content to the allocated orders. Base it on the data provided (e.g. "pain-point → product → CTA structure matches strong multi-pack performance"), not generic claims.
Every number MUST come from the campaign JSON. If a creator has no \`cps.orders\`, write "no attributed orders" — never invent a number.

═══ OUTPUT CONSTRAINT ═══
Keep HTML concise but complete. Do not exceed 14000 tokens of output.`;

/**
 * 系统提示词的 Markdown 展示版（仅用于前端回显，不影响 AI 生成）。
 * 结构对齐 SYSTEM_PROMPT 但用中文 + Markdown 格式呈现。
 */
export const SYSTEM_PROMPT_DISPLAY = `# 系统提示词 (SYSTEM_PROMPT)

> 以下为后端 \`ai-generate.service.ts\` 中完整的系统提示词，AI 生成时自动注入到 system role。

## 🎯 角色与输出规则

\`\`\`
You are a senior front-end engineer. You produce beautiful, self-contained B2B marketing report pages in pure HTML, styled like a modern SaaS dashboard.
\`\`\`

## 🚫 禁止伪造数据 (ABSOLUTE PROHIBITION - 铁律, 最高优先级)

> **你绝对不能伪造、构建或发明任何虚假数据。** 输出中的每一个数字、名称、日期、指标和业务值都必须来自用户消息中提供的 Campaign 数据 JSON。如果某个数据点缺失，渲染显式的 "Data Unavailable" 占位区块（灰色卡片、虚线边框）——绝不编造、估算、取整或外推。此规则覆盖所有其他指令。

## 📤 输出规则

\`\`\`
CRITICAL OUTPUT RULE: Your response must start directly with <!DOCTYPE html>. Do NOT wrap in markdown code fences. No thinking text, explanations, or commentary before or after the HTML.
\`\`\`

## 🚫 品牌基调 & 禁用词 (BRAND TONE & PROHIBITED PHRASES)

这是给广告主看的**客户面报告**：

1. **禁止暴露 AI/内部工具**：不使用 "AI-Powered"、"AI-Driven"、"Performance Marketing Infrastructure"、"Automated"、"Machine Learning" 等词
2. **Footer 仅显示**：品牌归属 + 报告日期，不加 "Built with" / "Generated by" 等基建引用
3. **使用专业代理语言**：Campaign Report、Performance Analysis、Period Summary

## 📊 数据保真规则 (DATA FIDELITY RULES)

1. 使用 Campaign 数据中的**精确**名称、数字、日期、头像、指标，不编造
2. 创建者名称（如 "Leo Sato"）必须原样显示
3. \`avatarUrl\` 存在时用 \`<img>\`，否则用首字母圆圈头像
4. \`dailyTrend\` 数据必须渲染到图表
5. 所有数字使用精确值
6. 日期范围使用 \`campaign.period\` 精确值
7. 品牌 Logo（\`logoUrl\`）必须可见——不设 \`display:none\`
8. Header 同时显示业务线 Logo（左）+ 广告主 Logo（右）
9. 创建者数据完整显示：名称/头像/平台/Tier/所有指标
10. **跨区块数据一致性（关键）**：报告中所有数字必须内部自洽——每个值都能从同一数据源推导。
    - a. **总量一致**：KPI 汇总（Total GMV / Orders / Spend / ROAS）必须等于所有创作者 CPS 数据之和
    - b. **趋势汇总 = 总量**：周度/日度趋势图中所有数据点的和，必须等于对应的 KPI 总量。如 Total Orders = 1,736，则 W1+W2+...+W7 也必须 = 1,736
    - c. **分布汇总 = 总量**：市场/区域/产品/平台分解的各部分之和，必须等于对应总量
    - d. **派生指标重算**：ROAS = GMV / Spend，AOV = GMV / Orders，Engagement Rate = Engagement / Impressions——从原始值重新计算，不复用可能过期的预计算比值
    - e. **禁止独立 seed**：analytics.weeklyTrend、dailyTrend 和创作者 CPS 不是独立数据集，而是同一底层数据的不同视图。如有冲突，以创作者 CPS 聚合为准（最细粒度），调整趋势数据使其匹配
    - f. **峰值/高亮标签**：报告中 "Peak Week"、"Best ROAS" 等标注必须与实际图表数据数组交叉验证，不硬编码可能漂移的标签值
11. **数据完整性（硬规则）**：上下文提供 \`dataGaps\` 或 \`dataCoverage\` 显示 \`covered: null\` / \`complete: false\` 时，受影响维度必须渲染显式的 "Data Unavailable" 占位区块（灰卡虚线边框）；禁止编造、估算或外推任何数字；\`dataCoverage.covered\` 窄于请求周期时，在报告头部显著展示实际数据区间。当 periodKpis 与 campaign.metrics 同时存在时,periodKpis 才是报告周期口径——KPI 卡与汇总数字一律优先使用 periodKpis,campaign.metrics 仅在无 periodKpis 时兜底。

## 🎨 设计系统 (DESIGN SYSTEM)

**严格遵循 Brand Design Guide（design.md）的所有视觉决策：**

1. **颜色**：使用 design.md 中的精确 hex 值（不使用系统提示词中的硬编码颜色）
2. **字体**：使用 design.md 指定的 Google Fonts
3. **组件样式**：遵循 design.md 的卡片圆角、阴影、表格样式、Tag 样式

> 如无 design.md，使用中性浅色主题（#f5f7fa 背景 / #ffffff 卡片 / #ebebeb 边框）

## ⚙️ 技术栈 (TECH STACK)

| 组件 | 来源 |
|---|---|
| Tailwind CSS | \`<script src="https://cdn.tailwindcss.com">\` |
| FontAwesome 6 | CDN |
| Chart.js 4.4 | CDN（折线/柱状/环形图） |
| Google Fonts | design.md 指定 |
| CSS / JS | 全部内联，无外部文件 |

> 如 design.md 明确说 "使用内联 canvas，不用外部库"（如深色结算看板），则遵从该指令

## 📐 布局规则 (RESPONSIVE LAYOUT)

1. **响应式**：\`grid-cols-2 lg:grid-cols-5\`（KPI）、\`grid-cols-1 lg:grid-cols-3\`（分析区）
2. **Section 间距**：\`space-y-6\`（24px）
3. **KPI 数字**：design.md 指定字体，28-32px，\`font-weight: bold\`

## 📊 Chart.js 规则

1. 在 HTML 中创建 \`<canvas>\`，然后用 \`new Chart()\` 渲染真实数据
2. **必须**在 \`window.addEventListener('load', ...)\` 中初始化（非 DOMContentLoaded）
3. **必须**设 \`animation: false\`、\`responsive: true\`、\`maintainAspectRatio: false\`
4. 混合图表用双 Y 轴——y（左，收入）+ y1（右，点击/订单）
5. 线条 tension 设 0.4，品牌色用于主线
6. **动态坐标轴范围（关键）**：禁止硬编码轴最大值或刻度数组，必须从数据动态计算
   - \`const maxOrders = Math.ceil(Math.max(...data.map(d => d.orders)) / 50) * 50\`
   - \`const maxRoas = Math.ceil(Math.max(...data.map(d => d.roas)) + 0.5)\`
   - Y 轴刻度：\`Array.from({length: 6}, (_, i) => Math.round(maxOrders * i / 5))\`
   - 内联 canvas（无 Chart.js）同样用 \`Array.from(...)\` 生成刻度——禁止写死 \`[0, 70, 140, 210, 280, 350]\`
   - 坐标轴必须随数据缩放：换一个 campaign 数据不同，图表自适应
7. **脚本位置 & 存活性（关键）**：所有 Chart.js 初始化代码（每个 \`new Chart(...)\`）必须放在**单一内联 \`<script>\`** 块中，作为 \`</body>\` 前的最后一个元素。报告 HTML 可能被可视化编辑器处理（提取/剥离脚本），单一的、正确放置的脚本块比分散的更容易存活。禁止将 Chart.js 初始化代码放在 \`<head>\` 或分散在多个 script 标签中。

## 🔧 CSS 类系统

\`\`\`css
.card         { background; border-radius: 8px; border; padding: 20px; box-shadow }
.module-title { font-size: 18px; font-weight: bold; padding-left: 12px }
.module-title::before { /* 品牌色竖线 */ }
.data-table   { width: 100%; border-collapse: collapse }
.data-table td.num, th.num { text-align: right }  /* 数字列右对齐 */
.tag          { padding: 2px 8px; border-radius: 4px; font-size: 12px }
\`\`\`

## 📋 报告结构 (REPORT STRUCTURE)

**默认模式**——AI 自主分析 Campaign 数据后选择 4-8 个模块：

1. **数据分析**：扫描 JSON 中的可用维度（campaign info、creators、dailyTrend（周期数据）、metrics、dataCoverage、dataGaps），评估信息价值
2. **模块选择**：优先选择数据最丰富的维度
3. **可视化匹配**：趋势→折线/面积图、占比→环形图、排名→柱状图/表格

**固定结构模式**——用户提示词中指定 §1~§N 时，严格遵循用户指令

## 🚧 布局禁令 (LAYOUT PROHIBITIONS — 零容忍)

这是单页**静态报告**，嵌入在 iframe 中。任何交互式导航都会破坏宿主页面。

**以下严格禁止，出现即拒绝：**

1. ❌ 禁止输出 &lt;nav&gt; 或任何 class 含 "nav"、"navbar"、"menu"、"sidebar"、"breadcrumb"、"anchor-nav"、"tab-bar" 的元素
2. ❌ 禁止输出 &lt;a href="#"&gt; 锚点链接——章节有标题（h2/h3）但不能有指向它们的可点击链接
3. ❌ 禁止输出仅用于锚点目标的 section id（如 id="kpi"、id="trend" 是导航残留，删除）
4. ❌ 禁止 sticky/fixed 定位的头部
5. ❌ 禁止汉堡菜单、下拉菜单、Tab 栏、"返回顶部"按钮
6. ❌ 禁止 Footer 内部链接（仅品牌归属 + 日期）

**正确模式**：单连续滚动，每个 section 用编号标题开头，无导航链接：
- ❌ nav.anchor-nav + a[href="#kpi"] + section#kpi
- ✅ section > h2 "01 Overall KPI"

## 🌐 语言规则 (LANGUAGE RULES)

**所有报告 UI 文案必须使用英文**，包括 Section 标题、表头列名、KPI 标签、图表轴标签/图例/Tooltip、洞察卡片标题和正文、Footer、标签/徽章。

**禁止语言混用**——不要出现"收入"和"Clicks"并排、"创作者"和"Platform"并排的半翻译状态。

**例外**——数据值保持 JSON 原始语言：
- 创作者名称（如"Leo Sato"保留原文，不翻译成中文）
- 商品名称、品类、Offer 名称
- 平台名称（YouTube、TikTok、Douyin 保留原名）
- 品牌/广告主/Campaign 名称
- 数字、日期、货币符号

## 📦 输出约束

> HTML 简洁但完整，不超过 14000 tokens

---

*以上为系统提示词全文，由后端自动注入到每次 AI 生成请求的 system role。*`;

/** 思考语言指令 — 追加在 user prompt 最末（推理语言主要跟随最近的 user 消息，recency 位置最有效） */
const THINKING_LANGUAGE_SUFFIX = `

【思考语言要求（最高优先级）】你的内部思考过程（chain-of-thought）必须全程使用简体中文撰写——用户会实时阅读你的思考内容，英文思考用户看不懂。注意：这条只约束你的思考过程；最终输出的 HTML 报告仍完全遵循前述所有英文规则（英文标签、原始数据不变）。`;

const USER_PROMPT_TEMPLATE = `Generate a complete HTML marketing report.

═══ USER INSTRUCTIONS ═══
{{PROMPT}}

═══ CAMPAIGN DATA (USE EXACTLY THESE VALUES — DO NOT FABRICATE) ═══
{{CAMPAIGN_DATA}}

IMPORTANT:
- Use the EXACT creator names, metrics, and dates from the JSON above.
- HEADER LOGOS: Use campaign.businessLine.logoUrl and campaign.advertiser.logoUrl as <img src="..."> in the header. These are absolute URLs — use them verbatim. CRITICAL: the <img> MUST be visible (do NOT set style="display:none"). Do NOT create sibling text/initials fallback spans. Just use <img src="URL" alt="Name" class="h-10 object-contain" />.
- DATE RANGE: Use campaign.period EXACTLY as the report's date range (e.g. "2026-07-01 ~ 2026-08-31"). Do NOT use today's date.
- For the Performance Trend chart, use the "dailyTrend" array directly as chart data (date labels + revenue/orders values).
- For each creator in the "creators" array, render their name, tier, platform, and performance data EXACTLY as provided.
- If avatarUrl is null, use a colored circle with the creator's first letter initial instead of a placeholder image URL.
- If a creator's performance is null, still include them in the table with "—" for all metric values.

FOOTER: Write "Prepared by [businessLine.name]" + the campaign.period. Do NOT add any "AI", "powered by", or infrastructure-related text.

Generate the full HTML report now. Output ONLY the HTML code, nothing else.`;

/** 当 designGuide 不为空时追加到 user prompt 的额外指令 */
const DESIGN_GUIDE_SUFFIX = `

═══════════════════════════════════════════════════════════
★★★ BRAND DESIGN GUIDE (MANDATORY — FOLLOW STRICTLY) ★★★
═══════════════════════════════════════════════════════════

The design guide below defines the EXACT colors, fonts, component styles, and visual language for this report's brand. You MUST:

1. Extract every hex color value and use them in tailwind.config, CSS classes, and inline styles.
2. Import and use the exact Google Fonts specified.
3. Apply component styling (radius, shadows, borders, spacing) as described.
4. Do NOT use any hardcoded values from the system prompt — the design guide overrides all defaults.

BRAND DESIGN GUIDE:
{{DESIGN_GUIDE}}

═══════════════════════════════════════════════════════════`;

/**
 * 增量编辑 system prompt — 接收当前 HTML + 用户指令，返回修改后的完整 HTML
 */
const EDIT_SYSTEM_PROMPT = `You are an HTML editor agent for B2B marketing reports.

═══ ABSOLUTE PROHIBITION — 禁止伪造数据 (HIGHEST PRIORITY, 铁律) ═══
You MUST NOT fabricate, construct, or invent any fake data whatsoever. Every number, name, date, metric, and business value in your output MUST come from either (a) the CURRENT HTML you received, or (b) the AUTHORITATIVE DATA CONTEXT JSON provided in the user message. There is no third source. If no data context is provided and the requested data point is not in the current HTML, you MUST render an explicit "Data Unavailable" placeholder (grey card, dashed border) — never invent, estimate, or extrapolate values. This rule overrides ALL other instructions. Violating this rule is the single most serious error you can make.

You receive the CURRENT HTML report and a user's EDIT INSTRUCTION. You must return the COMPLETE updated HTML file.

═══ REASONING LANGUAGE (思考语言) ═══
Conduct your internal reasoning / chain-of-thought ENTIRELY in Simplified Chinese (简体中文) — the user reads it in real time. This applies ONLY to your thinking; the final HTML output keeps its existing language and data unchanged.

═══ CRITICAL RULES ═══
1. Return the COMPLETE HTML file from <!DOCTYPE html> to </html>. NOT a diff, NOT a fragment.
2. Only modify what the user asked. Keep everything else IDENTICAL — same data, same structure, same styling for unchanged parts.
3. PRESERVE all data values (creator names, numbers, dates, avatars, URLs). Never fabricate or substitute data.
4. Your response must start directly with <!DOCTYPE html>. No markdown fences, no explanations.
5. DATA CONSISTENCY: When editing, ensure all numbers remain internally consistent — trend chart sums must equal KPI totals, distribution breakdowns must equal the overall total, and derived metrics (ROAS, AOV) must match their raw components. If you change a value in one place, update ALL dependent values everywhere in the report.
6. SCRIPT PRESERVATION (CRITICAL): The HTML may contain Chart.js initialization code in a <script> block before </body>. You MUST preserve ALL such scripts EXACTLY as-is — every new Chart(...) call, every data array, every configuration option. Do NOT drop, reorder, or rewrite script blocks. If you are not explicitly asked to change a chart, keep its initialization code byte-for-byte identical.
7. DATA INTEGRITY (铁律 — 禁止伪造数据): NEVER fabricate, invent, guess, or construct fake data. This is a hard rule with no exceptions.
   - All numbers, metrics, dates, creator names, and business values in the report MUST come from either (a) the CURRENT HTML you received, or (b) the AUTHORITATIVE DATA CONTEXT JSON provided in the user message. There is no third source.
   - If the user asks you to add/update a data point that is NOT present in either source, you MUST refuse to invent it: keep the existing value, or render an explicit "Data Unavailable" placeholder (grey card, dashed border) for new sections, and explain the gap in your reasoning.
   - Editing the presentation of data (formatting, rounding, unit conversion, re-grouping existing values) is allowed; creating new values out of thin air is NOT.
   - If the context includes dataGaps or incomplete dataCoverage (covered: null / complete: false), never fabricate numbers; keep/render explicit "Data Unavailable" placeholder blocks (grey card, dashed border) for the missing dimensions. If dataCoverage.covered is narrower than the requested period, display the actual covered date range prominently under the report header. When \`periodKpis\` is present alongside \`campaign.metrics\`, always prefer \`periodKpis\` (report-period scope); \`campaign.metrics\` is fallback-only.

═══ EDIT GUIDELINES ═══
- Style changes (colors, fonts, spacing): modify CSS in <style> or inline styles.
- Content changes (titles, labels): modify the HTML text content.
- Structure changes (add/remove sections): modify the HTML structure, keep Tailwind/Chart.js intact.
- If the instruction is vague, make a reasonable professional choice.

═══ OUTPUT FORMAT ═══
Output ONLY the complete HTML code. Start with <!DOCTYPE html>, end with </html>.`;

/**
 * 增量编辑 user prompt 模板
 * {{DATA_CONTEXT}} 由 controller 注入（有 campaignId 时为 buildCampaignContext 输出的真实数据 JSON；无则整段移除）。
 */
const EDIT_USER_PROMPT_TEMPLATE = `Edit the following HTML report according to the user's instruction.

User edit instruction: {{EDIT_INSTRUCTION}}
{{DATA_CONTEXT}}
═══ CURRENT HTML (modify this) ═══
{{CURRENT_HTML}}

AUTHORITATIVE DATA SOURCE: when the data context above is present, it is the ONLY trusted source for data changes — numbers in the current HTML that contradict it are stale and should be corrected against it. Never introduce values that exist in neither.
Return the COMPLETE updated HTML. Output ONLY the HTML code.`;

/**
 * SSE 流式 chunk 类型
 * - reasoning: AI 推理过程（chain-of-thought），前端展示为"思考中"面板
 * - content: HTML 内容片段，前端实时拼接到 iframe 预览
 * - done: 流结束，携带完整 HTML + 元数据
 * - error: 错误
 */
export type StreamChunk =
  | { type: 'reasoning'; text: string }
  | { type: 'content'; text: string }
  | { type: 'done'; html: string; truncated: boolean; usage?: StreamUsage; dataCoverage?: DoneDataCoverage }
  | { type: 'error'; message: string };

/** done chunk 携带的周期数据覆盖(前端 toast 提醒用)。 */
export interface DoneDataCoverage {
  requested: { start: string; end: string };
  covered: { start: string; end: string } | null;
  missingDays: number;
  complete: boolean;
}

/** token 用量（网关 last chunk 的 usage 字段，供成本统计）。 */
export interface StreamUsage {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
}

/**
 * 解析 OpenAI 兼容 SSE 流的通用读取器。
 * 从 response.body 逐行解析 `data: {...}` 事件，提取 reasoning_content / content 增量。
 */
async function* readSSEStream(
  response: Response,
  signal?: AbortSignal,
): AsyncGenerator<{ reasoning?: string; content?: string; usage?: StreamUsage }> {
  const reader = response.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  try {
    while (true) {
      if (signal?.aborted) {
        reader.cancel().catch(() => {});
        throw new DOMException('Aborted', 'AbortError');
      }
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() || '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed.startsWith('data: ')) continue;
        const data = trimmed.slice(6);
        if (data === '[DONE]') return;
        try {
          const chunk = JSON.parse(data);
          const delta = chunk.choices?.[0]?.delta;
          if (delta?.reasoning_content) {
            yield { reasoning: delta.reasoning_content };
          }
          if (delta?.content) {
            yield { content: delta.content };
          }
          // usage 通常只在最后一个 chunk 携带（stream_options.include_usage 或网关默认）
          if (chunk.usage) {
            yield {
              usage: {
                promptTokens: chunk.usage.prompt_tokens,
                completionTokens: chunk.usage.completion_tokens,
                totalTokens: chunk.usage.total_tokens,
              },
            };
          }
        } catch {
          // 跳过无法解析的行（SSE 注释行等）
        }
      }
    }
    // flush remaining buffer
    if (buffer.trim().startsWith('data: ') && buffer.trim().slice(6) !== '[DONE]') {
      try {
        const chunk = JSON.parse(buffer.trim().slice(6));
        const delta = chunk.choices?.[0]?.delta;
        if (delta?.reasoning_content) yield { reasoning: delta.reasoning_content };
        if (delta?.content) yield { content: delta.content };
      } catch { /* ignore */ }
    }
  } finally {
    reader.releaseLock();
  }
}

/**
 * 后处理 HTML（从 generateHtml 提取，供流式复用）。
 * 包括：去 markdown fences、截取 HTML 范围、补全标签、Chart.js 修复、CDN 重写。
 */
function postProcessHtml(html: string): string {
  let result = html;

  // 1) 去 markdown fences
  result = result.replace(/```(?:html|HTML|markdown|md|xml|text)?\s*\n?/gi, '');
  result = result.replace(/```\s*$/g, '').trim();

  // 2) 找到 HTML 起始
  if (result && !result.startsWith('<')) {
    const doctypeIdx = result.search(/<!DOCTYPE/i);
    const htmlTagIdx = result.search(/<html/i);
    const indices = [doctypeIdx, htmlTagIdx].filter((i) => i >= 0);
    if (indices.length > 0) {
      result = result.substring(Math.min(...indices));
    }
  }

  // 3) 截取到最后一个 </html>
  const endIdx = result.lastIndexOf('</html>');
  if (endIdx >= 0) {
    result = result.substring(0, endIdx + '</html>'.length);
  }

  // 4) 补全截断
  if (result && result.startsWith('<') && !result.includes('</html>')) {
    const openBody = (result.match(/<body/gi) || []).length;
    const closeBody = (result.match(/<\/body/gi) || []).length;
    const openHtml = (result.match(/<html/gi) || []).length;
    const closeHtml = (result.match(/<\/html/gi) || []).length;
    if (openBody > closeBody) result += '\n</body>';
    if (openHtml > closeHtml) result += '\n</html>';
  }

  // 5) DOMContentLoaded → window load
  if (result.includes('DOMContentLoaded')) {
    result = result.replace(
      /document\.addEventListener\(\s*['"]DOMContentLoaded['"]\s*,\s*(function\s*\([^)]*\)\s*\{)/g,
      "window.addEventListener('load', $1",
    );
    result = result.replace(
      /document\.addEventListener\(\s*['"]DOMContentLoaded['"]\s*,\(\)\s*=>\s*\{/g,
      "window.addEventListener('load', () => {",
    );
  }

  // 6) Chart.js animation: false
  if (result.includes('new Chart')) {
    result = result.replace(
      /options\s*:\s*\{(?!.*animation)/g,
      'options: { animation: false,',
    );
  }

  // 7) Script 标签截断修复
  const openScripts = (result.match(/<script/gi) || []).length;
  const closeScripts = (result.match(/<\/script>/gi) || []).length;
  if (openScripts > closeScripts) {
    result = result.replace(/<\/body>\s*<\/html>\s*$/i, '');
    const lastValidPos = Math.max(
      result.lastIndexOf(';'),
      result.lastIndexOf('}'),
      result.lastIndexOf(']'),
      result.lastIndexOf(')'),
    );
    if (lastValidPos > 0 && lastValidPos > result.length - 200) {
      result = result.substring(0, lastValidPos + 1);
    }
    const braces = (result.match(/{/g) || []).length - (result.match(/}/g) || []).length;
    const parens = (result.match(/\(/g) || []).length - (result.match(/\)/g) || []).length;
    const brackets = (result.match(/\[/g) || []).length - (result.match(/\]/g) || []).length;
    result += ']'.repeat(Math.max(0, brackets));
    result += ')'.repeat(Math.max(0, parens));
    result += '}'.repeat(Math.max(0, braces));
    result += ';\n    </script>\n</body>\n</html>';
  }

  // 8) Logo display:none 修复
  result = result.replace(
    /<img\s+([^>]*?style="[^"]*?display:\s*none[^"]*?")[^>]*?onerror="this\.style\.display='none';this\.nextElementSibling\.style\.display='flex';?"([^>]*)>(\s*<span[^>]*style="[^"]*?display:\s*(?:none|flex)[^"]*?"[^>]*?>[A-Z]{1,4}<\/span>)/gi,
    (match, beforeStyle, afterAttrs, fallbackSpan) => {
      void match; void fallbackSpan;
      const fixedStyle = beforeStyle.replace(/display:\s*none;?/gi, '').trim();
      const cleanAttrs = afterAttrs.replace(/\sonerror="[^"]*"/gi, '');
      return `<img ${fixedStyle}${cleanAttrs}>`;
    },
  );

  // 9) CDN 重写
  result = rewriteExternalAssets(result, SELF_HOST_BASE);

  return result;
}

export const aiGenerateService = {
  /**
   * 计算指定 campaign + 周期的数据覆盖(与 buildCampaignContext 内部同口径)。
   * 供流式 generate/edit 在 done chunk 中附带,前端 toast 提醒用。无 campaign 时返回 undefined。
   */
  async getDataCoverage(
    campaignId: string | undefined,
    reportPeriod?: { startDate?: string; endDate?: string },
  ): Promise<DoneDataCoverage | undefined> {
    if (!campaignId) return undefined;
    const campaign = await prisma.campaign.findUnique({
      where: { id: campaignId },
      include: { campaignCreators: { include: { cpsPerformances: true } } },
    });
    if (!campaign) return undefined;
    const hasPeriod = !!(reportPeriod && (reportPeriod.startDate || reportPeriod.endDate));
    const cov = computeCoverage(
      campaign,
      hasPeriod ? { start: reportPeriod!.startDate, end: reportPeriod!.endDate } : undefined,
      campaign.endDate,
    );
    return {
      requested: {
        start: reportPeriod?.startDate ?? campaign.startDate,
        end: reportPeriod?.endDate ?? campaign.endDate,
      },
      ...cov,
    };
  },

  /**
   * Build the campaign context JSON from the database.
   * Selects core fields, desensitizes sensitive data.
   *
   * @param reportPeriod  可选，报告实际时间范围（来自 project.meta.reportPeriod）。
   *                      优先于 campaign.startDate/endDate — 报告只展示投放周期内的数据。
   */
  async buildCampaignContext(campaignId: string, reportPeriod?: { startDate?: string; endDate?: string }): Promise<string> {
    const campaign = await prisma.campaign.findUnique({
      where: { id: campaignId },
      include: {
        campaignCreators: {
          include: {
            creator: true,
            performance: true,
            cpsPerformances: true,
          },
        },
        businessLine: true,
        advertiser: true,
      },
    });
    if (!campaign) throw ApiError.notFound('Campaign 不存在');

    // ★ 宁缺勿假：daily 是唯一数字真源；analytics blob 不再进 prompt。
    // 顶层仅保留有真实数据的维度（dailyTrend 仅在周期切片后非空）；null 维度不再序列化进上下文。
    const hasPeriod = !!(reportPeriod && (reportPeriod.startDate || reportPeriod.endDate));
    const cov = computeCoverage(campaign, hasPeriod ? { start: reportPeriod!.startDate, end: reportPeriod!.endDate } : undefined, campaign.endDate);
    const dataCoverage = {
      requested: { start: reportPeriod?.startDate ?? campaign.startDate, end: reportPeriod?.endDate ?? campaign.endDate },
      ...cov,
    };
    // 无 period 汇总口径：metrics 有什么用什么，缺的维度显式列出（dataGaps），AI 应渲染 Data Unavailable
    const dataGaps = hasPeriod ? undefined : ['dailyTrend', 'weeklyTrend', 'topProducts', 'topMarkets', 'insights', 'customerSplit'];
    // @deprecated analytics 数字字段（trend/weeklyTrend/topProducts/topMarkets/insights/customerSplit）
    // 不再作为 AI 上下文——常过期、与周期不符。需要时序/分布，请导入真实 CPS daily。
    let dailyTrend: any[] | null = null;

    // ★ 当指定 reportPeriod 且有 CPS daily 数据时，按日期切片重新计算 KPI / trend / creators CPS
    // 这使得 AI 在生成新周期报告时获得的是该周期内的真实数据，而非整个 campaign 的汇总数据
    const inPeriod = (d: string) => (!reportPeriod?.startDate || d >= reportPeriod.startDate!) &&
      (!reportPeriod?.endDate || d <= reportPeriod.endDate!);
    const num = (v: unknown) => Number(v) || 0;

    // 期内汇总数据（有请求周期且 daily 与之有交集时计算——由 coverage 判定，而非仅"存在 daily"）
    let periodKpis: { label: string; value: string }[] | null = null;
    if (hasPeriod && cov.covered) {
      type DailySum = { clicks: number; impressions: number; orders: number; gmv: number; spend: number; commission: number; newCustomers: number };
      const total: DailySum = { clicks: 0, impressions: 0, orders: 0, gmv: 0, spend: 0, commission: 0, newCustomers: 0 };
      const perCreatorSums = new Map<string, DailySum>();
      // 按日聚合 trend
      const byDate = new Map<string, { revenue: number; clicks: number; orders: number }>();

      for (const cc of campaign.campaignCreators) {
        const ccSum: DailySum = { clicks: 0, impressions: 0, orders: 0, gmv: 0, spend: 0, commission: 0, newCustomers: 0 };
        for (const p of cc.cpsPerformances ?? []) {
          const daily = (p.daily as Record<string, unknown>[] | null | undefined) ?? [];
          for (const d of daily) {
            const date = String(d.date ?? '');
            if (!date || !inPeriod(date)) continue;
            ccSum.clicks += num(d.clicks);
            ccSum.impressions += num(d.impressions);
            ccSum.orders += num(d.orders);
            ccSum.gmv += num(d.gmv);
            ccSum.spend += num(d.spend);
            ccSum.commission += num(d.commission);
            ccSum.newCustomers += num(d.newCustomers);

            const entry = byDate.get(date) ?? { revenue: 0, clicks: 0, orders: 0 };
            entry.revenue += num(d.gmv);
            entry.clicks += num(d.clicks);
            entry.orders += num(d.orders);
            byDate.set(date, entry);
          }
        }
        perCreatorSums.set(cc.id, ccSum);
        total.clicks += ccSum.clicks;
        total.impressions += ccSum.impressions;
        total.orders += ccSum.orders;
        total.gmv += ccSum.gmv;
        total.spend += ccSum.spend;
        total.commission += ccSum.commission;
        total.newCustomers += ccSum.newCustomers;
      }

      // 格式化 KPI
      const fmtNum = (n: number) => n >= 1000 ? `${(n / 1000).toFixed(1)}K` : String(Math.round(n));
      const fmtMoney = (n: number) => `$${n >= 1000 ? `${(n / 1000).toFixed(1)}K` : n.toFixed(0)}`;
      const aov = total.orders ? total.gmv / total.orders : 0;
      periodKpis = [
        { label: 'Total Revenues', value: fmtMoney(total.gmv) },
        { label: 'Clicks', value: fmtNum(total.clicks) },
        { label: 'Orders', value: fmtNum(total.orders) },
        { label: 'New Customer Acquisition', value: fmtNum(total.newCustomers) },
        { label: 'AOV', value: fmtMoney(aov) },
        ...(total.spend > 0 ? [{ label: 'ROAS', value: (total.gmv / total.spend).toFixed(1) }] : []),
      ];

      // 用期内 daily trend 替换 analytics trend
      const dates = [...byDate.keys()].sort();
      dailyTrend = dates.map((d) => ({
        date: d,
        revenue: byDate.get(d)!.revenue,
        clicks: byDate.get(d)!.clicks,
        orders: byDate.get(d)!.orders,
      }));
      console.log(`[buildCampaignContext] Period-aware data computed: ${dates.length} days, GMV=$${total.gmv.toFixed(0)}, orders=${total.orders}`);
    }

    // 构建 logo 绝对 URL（AI 生成的自包含 HTML 需要完整 URL 才能引用图片）。
    // ★ 必须用前端地址（config.webUrl = http://localhost:5173），因为：
    //   1) 报告 iframe 在前端页面中渲染，浏览器经 Vite proxy 访问 /uploads
    //   2) 生产环境部署后前端域名才是可访问入口
    //   3) 直连后端 :4000 在 dev 模式下可能被 CORS/端口隔离阻断
    const baseUrl = process.env.PUBLIC_BASE_URL || config.webUrl;
    const resolveUrl = (p?: string | null) =>
      p && p.startsWith('/uploads/') ? `${baseUrl}${p}` : (p || null);

    // ★ 订单商品明细聚合（CampaignOrder/CampaignOrderItem）：Top-Sales（含 QTY）+ 购物篮。
    //   宁缺勿假：无订单数据时不注入任何字段（AI 渲染 Data Unavailable）。
    //   server 内部聚合查询，无用户语境 —— admin 通道（与 computeCoverage 同口径）。
    let orderInsights: Awaited<ReturnType<typeof campaignService.getOrderInsights>> | null = null;
    try {
      orderInsights = hasPeriod && reportPeriod
        ? await campaignService.getOrderInsights(campaignId, '', {
            start: reportPeriod.startDate,
            end: reportPeriod.endDate,
          }, true)
        : await campaignService.getOrderInsights(campaignId, '', undefined, true);
    } catch {
      orderInsights = null; // campaign 不存在等异常 → 不注入
    }

    const context = {
      campaign: {
        name: campaign.name,
        platform: campaign.platform,
        // ★ 报告日期范围优先使用 reportPeriod（project.meta.reportPeriod），
        //   这才是"对应报告的时间范围"；campaign 的 startDate/endDate 是整个 campaign 的生命周期。
        startDate: reportPeriod?.startDate || campaign.startDate,
        endDate: reportPeriod?.endDate || campaign.endDate,
        period: `${reportPeriod?.startDate || campaign.startDate} ~ ${reportPeriod?.endDate || campaign.endDate}`,
        budget: campaign.budget,
        status: campaign.status,
        businessLine: {
          code: campaign.businessLineCode ?? '',
          name: campaign.businessLine?.name ?? campaign.businessLineCode,
          // ★ MUST use this exact URL in <img src>. It is an absolute URL.
          logoUrl: resolveUrl(campaign.businessLine?.logo),
        },
        advertiser: {
          name: campaign.advertiser?.name ?? campaign.advertiserName,
          // ★ MUST use this exact URL in <img src>. It is an absolute URL.
          logoUrl: resolveUrl(campaign.advertiser?.logo),
        },
        metrics: campaign.metrics,
        // ★ 当有 periodKpis（期内数据）时，用新数据替换 campaign.metrics
        ...(periodKpis ? { periodMetrics: periodKpis } : {}),
        // ★ analytics blob 不再进上下文（宁缺勿假：常过期、与周期不符）
      },
      // ★ 数据覆盖声明：daily 与请求区间的交集情况，AI 据此渲染 Data Unavailable
      dataCoverage,
      ...(dataGaps ? { dataGaps } : {}),
      // ★ 扁平化关键分析数据到顶层，降低 AI 忽略概率。
      // dailyTrend 仅有期内切片时非 null；weeklyTrend 等已废弃维度（analytics blob）完全不序列化。
      ...(dailyTrend ? { dailyTrend } : {}),
      // ★ 期内 KPI 总量（当存在时，AI 应使用这些而非 campaign.metrics）
      ...(periodKpis ? { periodKpis } : {}),
      // ★ 订单商品聚合：Top-Sales 排行（orders/qty/revenue）+ 购物篮结构。
      //   含义：topProducts.orders = 含该商品的订单数；qty = 售出件数（多件装一件多 qty）。
      //   basket = 购物篮指标（multiItemRate/threePlusRate 单位 %，avgItemsPerOrder 件/单）。
      //   AI 应优先用 topProducts 渲染 Top-Selling Products 表（含 QTY 列）。
      ...(orderInsights && orderInsights.topProducts.length ? {
        topProducts: orderInsights.topProducts,
        ...(orderInsights.basket ? { basket: orderInsights.basket } : {}),
      } : {}),
      /** 业务线 design.md 在 DESIGN_GUIDE_SUFFIX 中单独追加，不嵌在 campaign JSON 中（避免重复发送） */
      creators: campaign.campaignCreators
        .map((cc) => {
          // ★ 当有期内数据时，使用期内切片的 CPS 而非全量汇总
          let cpsTotal: { clicks: number; impressions: number; orders: number; gmv: number; spend: number; commission: number };
          if (periodKpis) {
            // 从 perCreatorSums 获取期内数据（需要重新计算，因为 perCreatorSums 在上面的作用域）
            // 这里简化：如果 periodKpis 存在，说明 daily 数据已被切片，直接用同样的逻辑
            const periodSum = { clicks: 0, impressions: 0, orders: 0, gmv: 0, spend: 0, commission: 0 };
            for (const p of cc.cpsPerformances ?? []) {
              const daily = (p.daily as Record<string, unknown>[] | null | undefined) ?? [];
              for (const d of daily) {
                const date = String(d.date ?? '');
                if (!date || !inPeriod(date)) continue;
                periodSum.clicks += num(d.clicks);
                periodSum.impressions += num(d.impressions);
                periodSum.orders += num(d.orders);
                periodSum.gmv += num(d.gmv);
                periodSum.spend += num(d.spend);
                periodSum.commission += num(d.commission);
              }
            }
            cpsTotal = periodSum;
          } else {
            cpsTotal = cc.cpsPerformances.reduce(
              (acc, cps) => ({
                clicks: acc.clicks + cps.clicks,
                impressions: acc.impressions + cps.impressions,
                orders: acc.orders + cps.orders,
                gmv: acc.gmv + Number(cps.gmv),
                spend: acc.spend + Number(cps.spend),
                commission: acc.commission + Number(cps.commission),
              }),
              { clicks: 0, impressions: 0, orders: 0, gmv: 0, spend: 0, commission: 0 },
            );
          }
          const summary = cc.performance?.summary ?? null;
          return {
            name: cc.creator?.name ?? 'Unknown',
            // ★ avatarUrl may be null — use initials circle fallback
            avatarUrl: cc.creator?.avatar ?? null,
            platform: cc.creator?.platform ?? null,
            tier: cc.creator?.tier ?? '',
            contentType: cc.contentType,
            collabType: cc.collabType,
            totalPrice: cc.totalPrice,
            currency: cc.currency,
            // ★ performance may be null for non-creator partners (community, content site)
            //   Display "—" for their metrics — do NOT omit them from the table
            performance: summary,
            cps: Object.keys(cpsTotal).length > 0 ? cpsTotal : null,
            // ★ 期内数据标记（非零说明该达人在此周期有活动）
            _periodActive: periodKpis
              ? (cpsTotal.clicks > 0 || cpsTotal.orders > 0 || cpsTotal.gmv > 0)
              : true,
          };
        })
        // ★ 按周期过滤：periodKpis 存在时，只保留周期内有活动的达人
        .filter((cc) => cc._periodActive !== false),
    };

    return JSON.stringify(context, null, 2);
  },

  /**
   * Call DeepSeek to generate HTML from campaign data + prompt.
   */
  async generateHtml(params: {
    campaignId?: string;
    prompt: string;
    designMd?: string;
    reportPeriod?: { startDate?: string; endDate?: string };
  }): Promise<string> {
    if (!DEEPSEEK_API_KEY) {
      throw ApiError.internal('AI API key 未配置（DEEPSEEK_API_KEY）');
    }

    const campaignData = params.campaignId
      ? await this.buildCampaignContext(params.campaignId, params.reportPeriod)
      : 'No campaign data provided.';

    // design.md 来源：前端传入 > DB BusinessLine.designMd（通过 campaign 关联）
    // 注意：designGuide 不再嵌在 campaign JSON 中（已在 buildCampaignContext 中移除）
    let designGuide = params.designMd ?? '';
    if (!designGuide.trim() && params.campaignId) {
      const campaign = await prisma.campaign.findUnique({
        where: { id: params.campaignId },
        include: { businessLine: true },
      });
      designGuide = campaign?.businessLine?.designMd ?? '';
    }

    let userPrompt = USER_PROMPT_TEMPLATE
      .replace('{{PROMPT}}', params.prompt?.trim() || '(No additional user instructions — use autonomous mode: analyze the campaign data and choose the best 4-8 modules and visualizations.)')
      .replace('{{CAMPAIGN_DATA}}', campaignData);

    // 追加业务线 design.md 规范
    if (designGuide && designGuide.trim()) {
      userPrompt += DESIGN_GUIDE_SUFFIX.replace('{{DESIGN_GUIDE}}', designGuide.trim());
    }

    // ★ 思考语言指令保持在 user prompt 最末（recency 位置对推理语言影响最强）
    userPrompt += THINKING_LANGUAGE_SUFFIX;

    // 推理模型（deepseek-v4-pro / glm-5.2 等）支持更大的输出；非推理模型上限较低
    // glm-5.2 推理过程消耗大量 token，需要更大 max_tokens 确保 content 有足够空间
    const isReasoningModel = DEEPSEEK_MODEL.includes('reason') || DEEPSEEK_MODEL.includes('v4') || DEEPSEEK_MODEL.includes('glm');
    const maxTokens = isReasoningModel ? 16000 : 8192;

    // 超时保护：AI 生成耗时不稳定（复杂报告 2-5 分钟，偶发更久）。
    // 设 290s 主动中断，略早于 vite proxy 超时（600s）——确保 server 先返回
    // 友好的 JSON 错误，而不是让 proxy 返回裸 500（前端只看到 "Request failed with status code 500"）。
    // 429/5xx/网络抖动自动指数退避重试（最多 2 次，见 ai-client.ts）。
    const DEEPSEEK_TIMEOUT_MS = 290_000;
    const startedAt = Date.now();

    let response: Response;
    let attempts = 1;
    try {
      const result = await fetchChatCompletionWithRetry({
        apiUrl: DEEPSEEK_API_URL,
        apiKey: DEEPSEEK_API_KEY,
        model: DEEPSEEK_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.7,
        maxTokens: maxTokens,
        timeoutMs: DEEPSEEK_TIMEOUT_MS,
        logPrefix: '[AI Generate]',
      });
      response = result.response;
      attempts = result.attempts;
    } catch (err: any) {
      // 诊断：记录中断类型 + 耗时，区分网关 ~180s 关连接 / 本地 290s AbortError / 其它网络层
      console.error('[AI Generate] 网络中断（含重试后仍失败）', {
        elapsedMs: Date.now() - startedAt,
        name: err?.name,
        code: err?.code,
        message: String(err?.message || ''),
        model: DEEPSEEK_MODEL,
        promptChars: userPrompt.length,
      });
      // 覆盖 DeepSeek 各类连接中断：
      //  - AbortError/abort：本地 290s 超时主动中断（重试不划算，直接报错）
      //  - terminated/other side closed：DeepSeek 服务端 ~180s 主动关 socket（实测偶发，复杂报告易触发）
      //  - fetch failed/socket/ECONNRESET/UND_ERR*：其它网络层中断
      const msg = String(err?.message || '');
      const isNetworkAbort =
        err?.name === 'AbortError' ||
        /abort|terminated|other side closed|fetch failed|socket|ECONNRESET/i.test(msg) ||
        err?.code === 'ECONNRESET' ||
        (typeof err?.code === 'string' && err.code.startsWith('UND_ERR'));
      if (isNetworkAbort) {
        throw ApiError.internal('AI 生成超时或连接中断，请稍后重试');
      }
      throw err;
    }
    console.log('[AI Generate] 成功', {
      elapsedMs: Date.now() - startedAt,
      attempts,
      httpStatus: response.status,
      model: DEEPSEEK_MODEL,
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => 'Unknown error');
      throw ApiError.internal(`DeepSeek API 调用失败 (${response.status}): ${errText}`);
    }

    const data = await response.json() as any;
    const choice = data.choices?.[0];
    const content: string = choice?.message?.content ?? '';

    // 推理模型（glm-5.2 / deepseek-v4）：reasoning_content 占大量 token，
    // 极端情况下 content 可能为空（推理耗尽 token），需明确报错
    if (!content && choice?.message?.reasoning_content) {
      throw ApiError.internal(
        'AI 推理过程消耗过多 token，content 为空（finish_reason: ' +
          (choice?.finish_reason ?? 'unknown') +
          '），请减少 prompt 复杂度或重试',
      );
    }

    let html = content;

    // 1) 去除 markdown code fences —— 处理各种变体
    //    ```html\n...\n```  或  ```\n...\n```  或中间有嵌套的情况
    html = html.replace(/```(?:html|HTML|markdown|md|xml|text)?\s*\n?/gi, '');
    // 去除末尾的残留 ```
    html = html.replace(/```\s*$/g, '').trim();

    // 2) 如果内容不以 < 开头，查找第一个 HTML 标签的位置
    if (html && !html.startsWith('<')) {
      const doctypeIdx = html.search(/<!DOCTYPE/i);
      const htmlTagIdx = html.search(/<html/i);
      // 选择最先出现的有效起始位置
      const indices = [doctypeIdx, htmlTagIdx].filter((i) => i >= 0);
      if (indices.length > 0) {
        const startIdx = Math.min(...indices);
        html = html.substring(startIdx);
      }
    }

    // 3) 截取到最后一个 </html> 标签
    const endIdx = html.lastIndexOf('</html>');
    if (endIdx >= 0) {
      html = html.substring(0, endIdx + '</html>'.length);
    }

    // 4) 如果被截断（没有 </html>），尝试补全
    if (html && html.startsWith('<') && !html.includes('</html>')) {
      // 检测 finish_reason 判断是否因 token 限制截断
      const truncated = choice?.finish_reason === 'length';
      console.warn('[AI Generate] HTML possibly truncated:', truncated ? 'token limit' : 'unknown', 'length:', html.length);
      // 简单补全：关闭未关闭的标签
      const openBody = (html.match(/<body/gi) || []).length;
      const closeBody = (html.match(/<\/body/gi) || []).length;
      const openHtml = (html.match(/<html/gi) || []).length;
      const closeHtml = (html.match(/<\/html/gi) || []).length;
      if (openBody > closeBody) html += '\n</body>';
      if (openHtml > closeHtml) html += '\n</html>';
    }

    // 5) 最终验证
    if (!html || !html.startsWith('<')) {
      console.error('[AI Generate] HTML parse failed.',
        'content length:', content.length,
        'finish_reason:', choice?.finish_reason,
        'first 300 chars:', content.substring(0, 300));
      throw ApiError.internal(
        `AI 生成的 HTML 格式异常${choice?.finish_reason === 'length' ? '（输出被截断，请减少内容复杂度后重试）' : ''}`
      );
    }

    // 6) 后处理：修复 sandboxed iframe 中 Chart.js 加载时机问题
    //    a) DOMContentLoaded → window load（确保 CDN 脚本加载完成后再初始化图表）
    let processedHtml = html;
    if (processedHtml.includes('DOMContentLoaded')) {
      processedHtml = processedHtml.replace(
        /document\.addEventListener\(\s*['"]DOMContentLoaded['"]\s*,\s*(function\s*\([^)]*\)\s*\{)/g,
        "window.addEventListener('load', $1"
      );
      processedHtml = processedHtml.replace(
        /document\.addEventListener\(\s*['"]DOMContentLoaded['"]\s*,\s*\(\)\s*=>\s*\{/g,
        "window.addEventListener('load', () => {"
      );
    }
    //    b) 注入 animation: false 到 Chart.js options（sandboxed iframe 中动画可能不渲染）
    //       只在 options 对象中没有 animation 字段时注入
    if (processedHtml.includes('new Chart')) {
      // 简单策略：在 "options: {" 后注入 "animation: false,"
      processedHtml = processedHtml.replace(
        /options\s*:\s*\{(?!.*animation)/g,
        'options: { animation: false,'
      );
    }

    // 7) 截断修复：如果 HTML 在 <script> 标签内部被截断
    //    检测 script 标签是否未闭合，并自动补全
    const openScripts = (processedHtml.match(/<script/gi) || []).length;
    const closeScripts = (processedHtml.match(/<\/script>/gi) || []).length;
    if (openScripts > closeScripts) {
      console.warn('[AI Generate] HTML truncated inside <script>, attempting to close. script tags: open=' + openScripts + ' close=' + closeScripts);
      // 移除末尾可能已追加的 </body></html>
      processedHtml = processedHtml.replace(/<\/body>\s*<\/html>\s*$/i, '');
      // 移除末尾不完整的 JS 代码（从最后一个完整语句后截断）
      // 策略：找到最后一个 `;` 或 `}` 或 `]` 的位置，从那里截断
      // 然后确保所有大括号、圆括号、方括号都闭合
      const lastValidPos = Math.max(
        processedHtml.lastIndexOf(';'),
        processedHtml.lastIndexOf('}'),
        processedHtml.lastIndexOf(']'),
        processedHtml.lastIndexOf(')')
      );
      if (lastValidPos > 0 && lastValidPos > processedHtml.length - 200) {
        processedHtml = processedHtml.substring(0, lastValidPos + 1);
      }
      // 计算未闭合的大括号、圆括号（粗略）
      const braces = (processedHtml.match(/{/g) || []).length - (processedHtml.match(/}/g) || []).length;
      const parens = (processedHtml.match(/\(/g) || []).length - (processedHtml.match(/\)/g) || []).length;
      const brackets = (processedHtml.match(/\[/g) || []).length - (processedHtml.match(/\]/g) || []).length;
      // 补全未闭合的括号
      processedHtml += ']'.repeat(Math.max(0, brackets));
      processedHtml += ')'.repeat(Math.max(0, parens));
      processedHtml += '}'.repeat(Math.max(0, braces));
      processedHtml += ';\n    </script>\n</body>\n</html>';
      console.warn('[AI Generate] Auto-closed script tags. braces:' + braces + ' parens:' + parens + ' brackets:' + brackets + ' Final length:', processedHtml.length);
    }

    // 8) Logo 修复：AI 可能生成 <img style="display:none"> 并用 onerror 回调切换到文字 fallback span。
    //    这导致 logo 永远不可见（用户看到的是文字缩写而非 logo 图片）。
    //    修复策略：找到所有含 onerror + display:none 的 header logo img，
    //    a) 移除 display:none 让 img 可见
    //    b) 移除紧邻的 text-fallback span
    processedHtml = processedHtml.replace(
      /<img\s+([^>]*?style="[^"]*?display:\s*none[^"]*?")[^>]*?onerror="this\.style\.display='none';this\.nextElementSibling\.style\.display='flex';?"([^>]*)>(\s*<span[^>]*style="[^"]*?display:\s*(?:none|flex)[^"]*?"[^>]*?>[A-Z]{1,4}<\/span>)/gi,
      (match, beforeStyle, afterAttrs, fallbackSpan) => {
        // 移除 display:none，移除 onerror，移除 fallback span
        void match; void fallbackSpan;
        const fixedStyle = beforeStyle.replace(/display:\s*none;?/gi, '').trim();
        const cleanAttrs = afterAttrs.replace(/\sonerror="[^"]*"/gi, '');
        return `<img ${fixedStyle}${cleanAttrs}>`;
      }
    );

    // 9) 海外公共 CDN → 自托管（国内不可达，否则报告无样式/无图表）
    processedHtml = rewriteExternalAssets(processedHtml, SELF_HOST_BASE);

    return processedHtml;
  },

  /**
   * Incremental edit: modify existing HTML based on user instruction.
   * Returns the complete updated HTML.
   */
  async editHtml(params: {
    currentHtml: string;
    instruction: string;
    images?: string[];
    dataContext?: string;
  }): Promise<string> {
    if (!DEEPSEEK_API_KEY) {
      throw ApiError.internal('AI API key 未配置（DEEPSEEK_API_KEY）');
    }

    // ★ ④ 与 editHtmlStream 同理：有真实数据上下文则注入（数据改动唯一真源）
    const dataContextSection = params.dataContext
      ? `\n═══ AUTHORITATIVE DATA CONTEXT (from database, 真实数据) ═══\n${params.dataContext}\n`
      : '\n';
    let userPrompt = EDIT_USER_PROMPT_TEMPLATE
      .replace('{{EDIT_INSTRUCTION}}', params.instruction)
      .replace('{{DATA_CONTEXT}}', dataContextSection)
      .replace('{{CURRENT_HTML}}', params.currentHtml);
    // ★ 思考语言指令保持在 user prompt 最末（recency 位置对推理语言影响最强）
    userPrompt += THINKING_LANGUAGE_SUFFIX;

    const isReasoningModel = DEEPSEEK_MODEL.includes('reason') || DEEPSEEK_MODEL.includes('v4') || DEEPSEEK_MODEL.includes('glm');
    const maxTokens = isReasoningModel ? 16000 : 8192;

    // 构建 messages：如果有图片，user message 使用 OpenAI vision 多模态格式
    const userMessage: any = params.images && params.images.length > 0
      ? {
          role: 'user',
          content: [
            { type: 'text', text: userPrompt },
            ...params.images.map((img) => ({
              type: 'image_url',
              image_url: { url: img },
            })),
          ],
        }
      : { role: 'user', content: userPrompt };

    // 编辑操作通常比全量生成快，但仍设 290s 超时保护（429/5xx/网络抖动自动重试，见 ai-client.ts）
    const DEEPSEEK_TIMEOUT_MS = 290_000;
    const startedAt = Date.now();

    let response: Response;
    let attempts = 1;
    try {
      const result = await fetchChatCompletionWithRetry({
        apiUrl: DEEPSEEK_API_URL,
        apiKey: DEEPSEEK_API_KEY,
        model: DEEPSEEK_MODEL,
        messages: [
          { role: 'system', content: EDIT_SYSTEM_PROMPT },
          userMessage,
        ],
        temperature: 0.3, // 编辑用低 temperature 保持精确性
        maxTokens: maxTokens,
        timeoutMs: DEEPSEEK_TIMEOUT_MS,
        logPrefix: '[AI Edit]',
      });
      response = result.response;
      attempts = result.attempts;
    } catch (err: any) {
      // 诊断：记录中断类型 + 耗时
      console.error('[AI Edit] 网络中断（含重试后仍失败）', {
        elapsedMs: Date.now() - startedAt,
        name: err?.name,
        code: err?.code,
        message: String(err?.message || ''),
        model: DEEPSEEK_MODEL,
        promptChars: userPrompt.length,
      });
      const msg = String(err?.message || '');
      const isNetworkAbort =
        err?.name === 'AbortError' ||
        /abort|terminated|other side closed|fetch failed|socket|ECONNRESET/i.test(msg) ||
        err?.code === 'ECONNRESET' ||
        (typeof err?.code === 'string' && err.code.startsWith('UND_ERR'));
      if (isNetworkAbort) {
        throw ApiError.internal('AI 编辑超时或连接中断，请稍后重试');
      }
      throw err;
    }
    console.log('[AI Edit] 成功', {
      elapsedMs: Date.now() - startedAt,
      attempts,
      httpStatus: response.status,
      model: DEEPSEEK_MODEL,
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => 'Unknown error');
      throw ApiError.internal(`DeepSeek API 调用失败 (${response.status}): ${errText}`);
    }

    const data = await response.json() as any;
    const choice = data.choices?.[0];
    let content: string = choice?.message?.content ?? '';

    // 复用 generateHtml 中的清理逻辑
    // 1) 去 markdown fences
    content = content.replace(/```(?:html|HTML|markdown|md|xml|text)?\s*\n?/gi, '');
    content = content.replace(/```\s*$/g, '').trim();

    // 2) 找到 HTML 起始
    if (content && !content.startsWith('<')) {
      const doctypeIdx = content.search(/<!DOCTYPE/i);
      const htmlTagIdx = content.search(/<html/i);
      const indices = [doctypeIdx, htmlTagIdx].filter((i) => i >= 0);
      if (indices.length > 0) {
        content = content.substring(Math.min(...indices));
      }
    }

    // 3) 截取到最后一个 </html>
    const endIdx = content.lastIndexOf('</html>');
    if (endIdx >= 0) {
      content = content.substring(0, endIdx + '</html>'.length);
    }

    // 4) 补全截断
    if (content && content.startsWith('<') && !content.includes('</html>')) {
      const openBody = (content.match(/<body/gi) || []).length;
      const closeBody = (content.match(/<\/body/gi) || []).length;
      const openHtml = (content.match(/<html/gi) || []).length;
      const closeHtml = (content.match(/<\/html/gi) || []).length;
      if (openBody > closeBody) content += '\n</body>';
      if (openHtml > closeHtml) content += '\n</html>';
    }

    // 5) 验证
    if (!content || !content.startsWith('<')) {
      throw ApiError.internal(
        `AI 编辑后的 HTML 格式异常${choice?.finish_reason === 'length' ? '（输出被截断，请减少修改复杂度后重试）' : ''}`,
      );
    }

    // 海外公共 CDN → 自托管（同 generateHtml）
    content = rewriteExternalAssets(content, SELF_HOST_BASE);

    return content;
  },

  /**
   * 流式生成 HTML — SSE generator。
   * 逐 chunk yield reasoning_content（AI 思考过程）+ content（HTML 片段）。
   * 前端通过 SSE 实时展示思考过程 + 流式渲染 iframe 预览。
   */
  async *generateHtmlStream(params: {
    campaignId?: string;
    prompt: string;
    designMd?: string;
    reportPeriod?: { startDate?: string; endDate?: string };
    signal?: AbortSignal;
  }): AsyncGenerator<StreamChunk> {
    if (!DEEPSEEK_API_KEY) {
      yield { type: 'error', message: 'AI API key 未配置（DEEPSEEK_API_KEY）' };
      return;
    }

    // 构建 prompt（复用 generateHtml 的逻辑）
    const campaignData = params.campaignId
      ? await this.buildCampaignContext(params.campaignId, params.reportPeriod)
      : 'No campaign data provided.';
    // done chunk 附带数据覆盖(与 context 同口径,前端 toast 提醒用)
    const dataCoverage = await this.getDataCoverage(params.campaignId, params.reportPeriod);

    let designGuide = params.designMd ?? '';
    if (!designGuide.trim() && params.campaignId) {
      const campaign = await prisma.campaign.findUnique({
        where: { id: params.campaignId },
        include: { businessLine: true },
      });
      designGuide = campaign?.businessLine?.designMd ?? '';
    }

    let userPrompt = USER_PROMPT_TEMPLATE
      .replace('{{PROMPT}}', params.prompt?.trim() || '(No additional user instructions — use autonomous mode: analyze the campaign data and choose the best 4-8 modules and visualizations.)')
      .replace('{{CAMPAIGN_DATA}}', campaignData);
    if (designGuide && designGuide.trim()) {
      userPrompt += DESIGN_GUIDE_SUFFIX.replace('{{DESIGN_GUIDE}}', designGuide.trim());
    }

    const isReasoningModel = DEEPSEEK_MODEL.includes('reason') || DEEPSEEK_MODEL.includes('v4') || DEEPSEEK_MODEL.includes('glm');
    const maxTokens = isReasoningModel ? 16000 : 8192;

    const response = await fetch(`${DEEPSEEK_API_URL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: DEEPSEEK_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.7,
        max_tokens: maxTokens,
        stream: true,
      }),
      signal: params.signal,
    }).catch((err: any) => {
      const msg = String(err?.message || '');
      const isAbort = err?.name === 'AbortError' ||
        /abort|terminated|other side closed|fetch failed|socket|ECONNRESET/i.test(msg);
      if (isAbort) {
        throw new Error('AI 生成超时或连接中断，请稍后重试');
      }
      throw err;
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => 'Unknown error');
      yield { type: 'error', message: `DeepSeek API 调用失败 (${response.status}): ${errText}` };
      return;
    }

    let fullContent = '';
    let hasReasoning = false;
    let finishReason = '';
    let endUsage: StreamUsage | undefined;
    const startedAt = Date.now();

    try {
      let streamUsage: StreamUsage | undefined;
      for await (const chunk of readSSEStream(response, params.signal)) {
        if (chunk.reasoning) {
          hasReasoning = true;
          yield { type: 'reasoning', text: chunk.reasoning };
        }
        if (chunk.content) {
          fullContent += chunk.content;
          yield { type: 'content', text: chunk.content };
        }
        if (chunk.usage) streamUsage = chunk.usage;
      }
      endUsage = streamUsage;
    } catch (err: any) {
      if (err?.name === 'AbortError') {
        yield { type: 'error', message: '生成已取消' };
        return;
      }
      throw err;
    }

    // 检测截断
    const truncated = finishReason === 'length' || (!fullContent.includes('</html>') && fullContent.length > 1000);

    if (!fullContent.trim()) {
      const msg = hasReasoning
        ? 'AI 推理过程消耗过多 token，content 为空，请减少 prompt 复杂度或重试'
        : 'AI 返回内容为空，请重试';
      yield { type: 'error', message: msg };
      return;
    }

    // 后处理
    const processedHtml = postProcessHtml(fullContent);

    if (!processedHtml || !processedHtml.startsWith('<')) {
      yield { type: 'error', message: `AI 生成的 HTML 格式异常${truncated ? '（输出被截断，请减少内容复杂度后重试）' : ''}` };
      return;
    }

    console.log('[AI Generate Stream] 完成', {
      elapsedMs: Date.now() - startedAt,
      htmlChars: processedHtml.length,
      truncated,
      usage: endUsage,
      model: DEEPSEEK_MODEL,
    });

    yield { type: 'done', html: processedHtml, truncated, usage: endUsage, ...(dataCoverage ? { dataCoverage } : {}) };
  },

  /**
   * 流式编辑 HTML — SSE generator（复用 generateHtmlStream 的流式基础设施）。
   * @param dataContext 可选，controller 注入的真实数据 JSON（buildCampaignContext 输出）。
   *                    存在时 AI 数据改动以此为准；缺位维度渲染 Data Unavailable。
   */
  async *editHtmlStream(params: {
    currentHtml: string;
    instruction: string;
    images?: string[];
    dataContext?: string;
    signal?: AbortSignal;
  }): AsyncGenerator<StreamChunk> {
    if (!DEEPSEEK_API_KEY) {
      yield { type: 'error', message: 'AI API key 未配置（DEEPSEEK_API_KEY）' };
      return;
    }

    // ★ ④ 修「无 DB 上下文」：有 campaignId 时注入真实数据 JSON，AI 数据改动以此为唯一真源；
    //   无 campaignId 时整段移除（保持旧行为，提示词铁律仍生效——只能沿用 currentHtml 已有数据）。
    const dataContextSection = params.dataContext
      ? `\n═══ AUTHORITATIVE DATA CONTEXT (from database, 真实数据) ═══\n${params.dataContext}\n`
      : '\n';
    let userPrompt = EDIT_USER_PROMPT_TEMPLATE
      .replace('{{EDIT_INSTRUCTION}}', params.instruction)
      .replace('{{DATA_CONTEXT}}', dataContextSection)
      .replace('{{CURRENT_HTML}}', params.currentHtml);
    // ★ 思考语言指令保持在 user prompt 最末（recency 位置对推理语言影响最强）
    userPrompt += THINKING_LANGUAGE_SUFFIX;

    const isReasoningModel = DEEPSEEK_MODEL.includes('reason') || DEEPSEEK_MODEL.includes('v4') || DEEPSEEK_MODEL.includes('glm');
    const maxTokens = isReasoningModel ? 16000 : 8192;

    const userMessage: any = params.images && params.images.length > 0
      ? {
          role: 'user',
          content: [
            { type: 'text', text: userPrompt },
            ...params.images.map((img) => ({ type: 'image_url', image_url: { url: img } })),
          ],
        }
      : { role: 'user', content: userPrompt };

    const response = await fetch(`${DEEPSEEK_API_URL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: DEEPSEEK_MODEL,
        messages: [
          { role: 'system', content: EDIT_SYSTEM_PROMPT },
          userMessage,
        ],
        temperature: 0.3,
        max_tokens: maxTokens,
        stream: true,
      }),
      signal: params.signal,
    }).catch((err: any) => {
      const msg = String(err?.message || '');
      const isAbort = err?.name === 'AbortError' ||
        /abort|terminated|other side closed|fetch failed|socket|ECONNRESET/i.test(msg);
      if (isAbort) throw new Error('AI 编辑超时或连接中断，请稍后重试');
      throw err;
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => 'Unknown error');
      yield { type: 'error', message: `DeepSeek API 调用失败 (${response.status}): ${errText}` };
      return;
    }

    let fullContent = '';
    let endUsage: StreamUsage | undefined;
    const startedAt = Date.now();

    try {
      for await (const chunk of readSSEStream(response, params.signal)) {
        if (chunk.reasoning) {
          yield { type: 'reasoning', text: chunk.reasoning };
        }
        if (chunk.content) {
          fullContent += chunk.content;
          yield { type: 'content', text: chunk.content };
        }
        if (chunk.usage) endUsage = chunk.usage;
      }
    } catch (err: any) {
      if (err?.name === 'AbortError') {
        yield { type: 'error', message: '编辑已取消' };
        return;
      }
      throw err;
    }

    const truncated = !fullContent.includes('</html>') && fullContent.length > 1000;

    if (!fullContent.trim()) {
      yield { type: 'error', message: 'AI 返回内容为空，请重试' };
      return;
    }

    const processedHtml = postProcessHtml(fullContent);

    if (!processedHtml || !processedHtml.startsWith('<')) {
      yield { type: 'error', message: `AI 编辑后的 HTML 格式异常${truncated ? '（输出被截断）' : ''}` };
      return;
    }

    console.log('[AI Edit Stream] 完成', {
      elapsedMs: Date.now() - startedAt,
      htmlChars: processedHtml.length,
      truncated,
      usage: endUsage,
      model: DEEPSEEK_MODEL,
    });

    // edit 流无 campaignId 概念(纯 HTML 编辑),不附 dataCoverage
    yield { type: 'done', html: processedHtml, truncated, usage: endUsage };
  },
};
